version: '2'

run:
  concurrency: 4
  go: '1.19'

linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - godot
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - maintidx
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - prealloc
    - recvcheck
    - revive
    - tagalign
    - tagliatelle
    - usestdlibvars
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      exclude-functions:
        - github.com/fastschema/fastschema/pkg/utils.WriteFile
        - io.Copy
        - (*ariga.io/atlas/sql/migrate.Planner).WritePlan
    funlen:
      lines: 150
      statements: 140
    gosec:
      excludes:
        - G115
        - G402
    staticcheck:
      checks:
        - all
        - -SA1029
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - gocritic
          - gosec
        path: _test\.go
      - linters:
          - funlen
        path: pkg/entdbadapter/query.go
      - linters:
          - govet
        path: schema/system_test.go
      - linters:
          - staticcheck
        path: \.go
        text: SA1019
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
