INSERT INTO categories (name, slug, created_at) VALUES
('Asia - Business & Finance', 'asia-business-finance', NOW()),
('Asia - Computers & IT Business', 'asia-computers-it-business', NOW()),
('Asia - Economics', 'asia-economics', NOW()),
('Asia - General News', 'asia-general-news', NOW()),
('Asia - Health, Medicine, Pharmacy Industry', 'asia-health-medicine-pharmacy-industry', NOW()),
('India - Computers & IT Business', 'india-computers-it-business', NOW()),
('India - Marketing, Advertising Trade', 'india-marketing-advertising-trade', NOW()),
('Accounting', 'accounting', NOW()),
('Advertising & Marketing', 'advertising-marketing', NOW()),
('Banking & Finance', 'banking-finance', NOW()),
('Business', 'business', NOW()),
('Business - Female Specific', 'business-female-specific', NOW()),
('Business Appointments', 'business-appointments', NOW()),
('Business Management', 'business-management', NOW()),
('Business Travel', 'business-travel', NOW()),
('Careers', 'careers', NOW()),
('Consumer Issues', 'consumer-issues', NOW()),
('Economics', 'economics', NOW()),
('Entrepreneurship', 'entrepreneurship', NOW()),
('Equity - Private & Public', 'equity-private-public', NOW()),
('Franchising', 'franchising', NOW()),
('Heavy Duty Transport & Cranes', 'heavy-duty-transport-cranes', NOW()),
('Innovation & Startup Policy', 'innovation-startup-policy', NOW()),
('Insurance', 'insurance', NOW()),
('Media & PR Trade', 'media-pr-trade', NOW()),
('Mining & Resources', 'mining-resources', NOW()),
('Money & Personal Finance', 'money-personal-finance', NOW()),
('Nonprofit, Charities, Fundraising', 'nonprofit-charities-fundraising', NOW()),
('Politics & Government', 'politics-government', NOW()),
('Politics & Government - Federal', 'politics-government-federal', NOW()),
('Politics & Government - Local', 'politics-government-local', NOW()),
('Politics & Government - State', 'politics-government-state', NOW()),
('Property - Commercial', 'property-commercial', NOW()),
('Property - Residential', 'property-residential', NOW()),
('Search Engine Marketing Industry', 'search-engine-marketing-industry', NOW()),
('Statistics', 'statistics', NOW()),
('Superannuation', 'superannuation', NOW()),
('Workplace Relations', 'workplace-relations', NOW()),
('Biotechnology & Life Science', 'biotechnology-life-science', NOW()),
('Business IT Analysts', 'business-it-analysts', NOW()),
('Chemistry', 'chemistry', NOW()),
('Computer Games', 'computer-games', NOW()),
('Computers & IT Business', 'computers-it-business', NOW()),
('Computers & IT Reseller', 'computers-it-reseller', NOW()),
('Consumer IT & Electronics', 'consumer-it-electronics', NOW()),
('Electronics, Robotics & Automation', 'electronics-robotics-automation', NOW()),
('Environment & Climate Change', 'environment-climate-change', NOW()),
('IT Programming', 'it-programming', NOW()),
('Mapping & Geospatial Industry', 'mapping-geospatial-industry', NOW()),
('Mobile & Wireless', 'mobile-wireless', NOW()),
('Science', 'science', NOW()),
('Security', 'security', NOW()),
('Solar Energy Industry', 'solar-energy-industry', NOW()),
('Technical Reviews', 'technical-reviews', NOW()),
('Telecommunications', 'telecommunications', NOW()),
('Waste & Water Management', 'waste-water-management', NOW()),
('Art & Culture', 'art-culture', NOW()),
('Books & Literature', 'books-literature', NOW()),
('Celebrity Gossip & Social', 'celebrity-gossip-social', NOW()),
('Entertainment', 'entertainment', NOW()),
('Movies', 'movies', NOW()),
('Music', 'music', NOW()),
('Performing Arts', 'performing-arts', NOW()),
('Photography', 'photography', NOW()),
('Television (consumer)', 'television-consumer', NOW()),
('Video/DVD Reviews', 'video-dvd-reviews', NOW()),
('Current Affairs/Features', 'current-affairs-features', NOW()),
('Feminism', 'feminism', NOW()),
('Foreign Affairs/World', 'foreign-affairs-world', NOW()),
('General News', 'general-news', NOW()),
('General News - ACT Only', 'general-news-act-only', NOW()),
('General News - NSW Only', 'general-news-nsw-only', NOW()),
('General News - NT Only', 'general-news-nt-only', NOW()),
('General News - QLD Only', 'general-news-qld-only', NOW()),
('General News - Radio', 'general-news-radio', NOW()),
('General News - SA Only', 'general-news-sa-only', NOW()),
('General News - TAS Only', 'general-news-tas-only', NOW()),
('General News - TV', 'general-news-tv', NOW()),
('General News - VIC Only', 'general-news-vic-only', NOW()),
('General News - WA Only', 'general-news-wa-only', NOW()),
('Indigenous Affairs', 'indigenous-affairs', NOW()),
('Investigative Reporting', 'investigative-reporting', NOW()),
('Migration', 'migration', NOW()),
('National Security', 'national-security', NOW()),
('Opinion', 'opinion', NOW()),
('Social Media & Data Journalists', 'social-media-data-journalists', NOW()),
('Society & Issues', 'society-issues', NOW()),
('Talkback & Talkshows', 'talkback-talkshows', NOW()),
('Urban Planning & Policy', 'urban-planning-policy', NOW()),
('Fitness & Wellbeing', 'fitness-wellbeing', NOW()),
('GWPR', 'gwpr', NOW()),
('Health Informatics', 'health-informatics', NOW()),
('Medicine & Health', 'medicine-health', NOW()),
('Medicine & Health - Dentistry', 'medicine-health-dentistry', NOW()),
('Medicine & Health - Arthritis', 'medicine-health-arthritis', NOW()),
('Medicine & Health - Asthma', 'medicine-health-asthma', NOW()),
('Medicine & Health - Diabetes', 'medicine-health-diabetes', NOW()),
('Medicine & Health - Disability', 'medicine-health-disability', NOW()),
('Medicine & Health - HIV', 'medicine-health-hiv', NOW()),
('Medicine & Health - Nursing', 'medicine-health-nursing', NOW()),
('Medicine & Health - Pharmacy', 'medicine-health-pharmacy', NOW()),
('Medicine & Health - Psychology & Psychotherapy', 'medicine-health-psychology-psychotherapy', NOW()),
('Medicine & Health - Spinal Cord Injuries', 'medicine-health-spinal-cord-injuries', NOW()),
('Medicine & Health - Vision & Hearing Impaired', 'medicine-health-vision-hearing-impaired', NOW()),
('Veterinary', 'veterinary', NOW()),
('Yoga', 'yoga', NOW()),
('Adventure & Outdoors', 'adventure-outdoors', NOW()),
('Adventure & Outdoors Photography', 'adventure-outdoors-photography', NOW()),
('Alternative & Spiritual Lifestyle', 'alternative-spiritual-lifestyle', NOW()),
('Animals & Pets', 'animals-pets', NOW()),
('Beauty & Personal Care', 'beauty-personal-care', NOW()),
('Beer & Brewing', 'beer-brewing', NOW()),
('Brides', 'brides', NOW()),
('Caravans', 'caravans', NOW()),
('Families & Parenting', 'families-parenting', NOW()),
('Fashion - Mens', 'fashion-mens', NOW()),
('Fashion - Womens', 'fashion-womens', NOW()),
('Food & Cuisine', 'food-cuisine', NOW()),
('Food Bloggers', 'food-bloggers', NOW()),
('Gardening', 'gardening', NOW()),
('History & Genealogy', 'history-genealogy', NOW()),
('Homes & Interiors', 'homes-interiors', NOW()),
('Inflight Magazine', 'inflight-magazine', NOW()),
('Kids Stuff', 'kids-stuff', NOW()),
('LGBT Lifestyle', 'lgbt-lifestyle', NOW()),
('Lifestyle', 'lifestyle', NOW()),
('Luxury Lifestyle', 'luxury-lifestyle', NOW()),
('Mens Interest', 'mens-interest', NOW()),
('Regional Tourism', 'regional-tourism', NOW()),
('Religion', 'religion', NOW()),
('Seniors Lifestyle', 'seniors-lifestyle', NOW()),
('Student Papers', 'student-papers', NOW()),
('Teen Women', 'teen-women', NOW()),
('Travel', 'travel', NOW()),
('Travel - Cruises', 'travel-cruises', NOW()),
('Wine & Liquor', 'wine-liquor', NOW()),
('Womens Interest', 'womens-interest', NOW()),
('Womens Lifestyle Bloggers', 'womens-lifestyle-bloggers', NOW()),
('Youth Culture', 'youth-culture', NOW()),
('Multicultural Press - African', 'multicultural-press-african', NOW()),
('Multicultural Press - Arabic', 'multicultural-press-arabic', NOW()),
('Multicultural Press - Armenian', 'multicultural-press-armenian', NOW()),
('Multicultural Press - Bangladesh', 'multicultural-press-bangladesh', NOW()),
('Multicultural Press - Bosnian', 'multicultural-press-bosnian', NOW()),
('Multicultural Press - Chinese', 'multicultural-press-chinese', NOW()),
('Multicultural Press - Croatian', 'multicultural-press-croatian', NOW()),
('Multicultural Press - Dutch', 'multicultural-press-dutch', NOW()),
('Multicultural Press - Finnish', 'multicultural-press-finnish', NOW()),
('Multicultural Press - French', 'multicultural-press-french', NOW()),
('Multicultural Press - Greek', 'multicultural-press-greek', NOW()),
('Multicultural Press - Indian', 'multicultural-press-indian', NOW()),
('Multicultural Press - Indonesian', 'multicultural-press-indonesian', NOW()),
('Multicultural Press - Iranian', 'multicultural-press-iranian', NOW()),
('Multicultural Press - Irish', 'multicultural-press-irish', NOW()),
('Multicultural Press - Italian', 'multicultural-press-italian', NOW()),
('Multicultural Press - Japanese', 'multicultural-press-japanese', NOW()),
('Multicultural Press - Jewish', 'multicultural-press-jewish', NOW()),
('Multicultural Press - Korean', 'multicultural-press-korean', NOW()),
('Multicultural Press - Lithuanian', 'multicultural-press-lithuanian', NOW()),
('Multicultural Press - Macedonian', 'multicultural-press-macedonian', NOW()),
('Multicultural Press - Maltese', 'multicultural-press-maltese', NOW()),
('Multicultural Press - Pacific Islander', 'multicultural-press-pacific-islander', NOW()),
('Multicultural Press - Polish', 'multicultural-press-polish', NOW()),
('Multicultural Press - Portuguese', 'multicultural-press-portuguese', NOW()),
('Multicultural Press - Russian', 'multicultural-press-russian', NOW()),
('Multicultural Press - Serbian', 'multicultural-press-serbian', NOW()),
('Multicultural Press - Spanish', 'multicultural-press-spanish', NOW()),
('Multicultural Press - Sri Lankan', 'multicultural-press-sri-lankan', NOW()),
('Multicultural Press - Turkish', 'multicultural-press-turkish', NOW()),
('Multicultural Press - Ukrainian', 'multicultural-press-ukrainian', NOW()),
('Multicultural Press - Vietnamese', 'multicultural-press-vietnamese', NOW()),
('NZ - Agriculture', 'nz-agriculture', NOW()),
('NZ - Accounting', 'nz-accounting', NOW()),
('NZ - Advertising, Marketing & Media', 'nz-advertising-marketing-media', NOW()),
('NZ - Art & Culture', 'nz-art-culture', NOW()),
('NZ - Beauty & Haircare', 'nz-beauty-haircare', NOW()),
('NZ - Building Trades', 'nz-building-trades', NOW()),
('NZ - Business', 'nz-business', NOW()),
('NZ - Computers & IT', 'nz-computers-it', NOW()),
('NZ - Entertainment', 'nz-entertainment', NOW()),
('NZ - Food & Cuisine', 'nz-food-cuisine', NOW()),
('NZ - General News', 'nz-general-news', NOW()),
('NZ - Health', 'nz-health', NOW()),
('NZ - House & Garden', 'nz-house-garden', NOW()),
('NZ - Lifestyle', 'nz-lifestyle', NOW()),
('NZ - Maori Affairs', 'nz-maori-affairs', NOW()),
('NZ - OHS', 'nz-ohs', NOW()),
('NZ - Politics & Government', 'nz-politics-government', NOW()),
('NZ - Travel', 'nz-travel', NOW()),
('NZ - Womens Interest', 'nz-womens-interest', NOW()),
('NZ Sport', 'nz-sport', NOW()),
('Athletics', 'athletics', NOW()),
('Australian Football League', 'australian-football-league', NOW()),
('Basketball', 'basketball', NOW()),
('Boating & Marine', 'boating-marine', NOW()),
('Bowls', 'bowls', NOW()),
('Boxing', 'boxing', NOW()),
('Cricket', 'cricket', NOW()),
('Cycling', 'cycling', NOW()),
('Cycling Associations - Global', 'cycling-associations-global', NOW()),
('Equestrian', 'equestrian', NOW()),
('Golf', 'golf', NOW()),
('Guns & Hunting', 'guns-hunting', NOW()),
('Gymnastics', 'gymnastics', NOW()),
('Hobbies & Crafts', 'hobbies-crafts', NOW()),
('Hockey', 'hockey', NOW()),
('Horse Racing', 'horse-racing', NOW()),
('Martial Arts', 'martial-arts', NOW()),
('Motorbike', 'motorbike', NOW()),
('Motoring', 'motoring', NOW()),
('Motorsports', 'motorsports', NOW()),
('Netball', 'netball', NOW()),
('Rugby', 'rugby', NOW()),
('Skateboarding', 'skateboarding', NOW()),
('Soccer', 'soccer', NOW()),
('Softball', 'softball', NOW()),
('Sport', 'sport', NOW()),
('Sport - Gossip', 'sport-gossip', NOW()),
('Sport - Womens', 'sport-womens', NOW()),
('Swimming & Watersports', 'swimming-watersports', NOW()),
('Tennis', 'tennis', NOW()),
('Winter Sports', 'winter-sports', NOW()),
('Aged Care', 'aged-care', NOW()),
('Architecture & Design', 'architecture-design', NOW()),
('Automotive Trade', 'automotive-trade', NOW()),
('Aviation & Aerospace', 'aviation-aerospace', NOW()),
('Beauty, Cosmetics & Hair Trade', 'beauty-cosmetics-hair-trade', NOW()),
('Broadcasting Industry', 'broadcasting-industry', NOW()),
('Building & Construction', 'building-construction', NOW()),
('Civil Engineering', 'civil-engineering', NOW()),
('Cleaning', 'cleaning', NOW()),
('Crime, Police & Courts', 'crime-police-courts', NOW()),
('Defence', 'defence', NOW()),
('Digital Design & Graphics', 'digital-design-graphics', NOW()),
('Education', 'education', NOW()),
('Education - Preschool', 'education-preschool', NOW()),
('Education - Schools', 'education-schools', NOW()),
('Education - Tertiary', 'education-tertiary', NOW()),
('Engineering', 'engineering', NOW()),
('Exports & Supply Chain', 'exports-supply-chain', NOW()),
('Fashion & Apparel Trade', 'fashion-apparel-trade', NOW()),
('Fire Prevention', 'fire-prevention', NOW()),
('Food, Snack & Beverage Trade', 'food-snack-beverage-trade', NOW()),
('Hotels, Clubs & Hospitality', 'hotels-clubs-hospitality', NOW()),
('Human Resources Professionals', 'human-resources-professionals', NOW()),
('Infrastructure', 'infrastructure', NOW()),
('Law', 'law', NOW()),
('Manufacturing', 'manufacturing', NOW()),
('Meetings & Trade Shows', 'meetings-trade-shows', NOW()),
('Music Industry', 'music-industry', NOW()),
('Obituaries & Funerals', 'obituaries-funerals', NOW()),
('Occupational Health & Safety', 'occupational-health-safety', NOW()),
('Polymers & Plastics', 'polymers-plastics', NOW()),
('Printing & Publishing', 'printing-publishing', NOW()),
('Retail Trade', 'retail-trade', NOW()),
('Rural & Agriculture', 'rural-agriculture', NOW()),
('Swimming Pools & Spas', 'swimming-pools-spas', NOW()),
('Television - Trade', 'television-trade', NOW()),
('Timber Trade', 'timber-trade', NOW()),
('Training', 'training', NOW()),
('Travel & Tourism Trade', 'travel-tourism-trade', NOW()),
('Truck, Bus, Rail & Heavy Machinery', 'truck-bus-rail-heavy-machinery', NOW()),
('UK - Computers & IT', 'uk-computers-it', NOW()),
('UK - Motoring', 'uk-motoring', NOW()),
('UK - Risk & Compliance', 'uk-risk-compliance', NOW()),
('US - Biotech', 'us-biotech', NOW()),
('US - Business Top 100 (by Circulation)', 'us-business-top-100-by-circulation', NOW()),
('US - Computer & IT Associations', 'us-computer-it-associations', NOW()),
('US - Computer Security', 'us-computer-security', NOW()),
('US - Computers & IT Business', 'us-computers-it-business', NOW()),
('US - Digital Gaming', 'us-digital-gaming', NOW()),
('US - Enterprise & Cloud', 'us-enterprise-cloud', NOW()),
('US - Entrepreneur & Startup', 'us-entrepreneur-startup', NOW()),
('US - Funding and M&A', 'us-funding-and-ma', NOW()),
('US - Health', 'us-health', NOW()),
('US - Information Technology', 'us-information-technology', NOW()),
('US - Logistics, Export, International Trade', 'us-logistics-export-international-trade', NOW()),
('US - Marketing Technology', 'us-marketing-technology', NOW()),
('US - Media & Entertainment Ventures', 'us-media-entertainment-ventures', NOW()),
('US - Mobile & Apps', 'us-mobile-apps', NOW()),
('US - Water & Environment', 'us-water-environment', NOW()),
('US - Wine & Liquor', 'us-wine-liquor', NOW())
