name: tests
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'dash/**'
      - 'pkg/dash/**'
    tags-ignore:
      - '*.*'
  pull_request:
    paths-ignore:
      - 'dash/**'
      - 'pkg/dash/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          args: --verbose

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.23.x', '1.24.x', '1.25.x']
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    services:
      mysql8:
        image: mysql:8
        env:
          MYSQL_DATABASE: fastschema
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3307:3306
        options: >-
          --health-cmd "mysqladmin ping -p123"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      mysql9:
        image: mysql:9
        env:
          MYSQL_DATABASE: fastschema
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3308:3306
        options: >-
          --health-cmd "mysqladmin ping -p123"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      mariadb10:
        image: mariadb:10
        env:
          MYSQL_DATABASE: fastschema
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3309:3306
        options: >-
          --health-cmd "mariadb-admin ping -h 127.0.0.1 -uroot -p123 --silent"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      mariadb11:
        image: mariadb:11
        env:
          MYSQL_DATABASE: fastschema
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3310:3306
        options: >-
          --health-cmd "mariadb-admin ping -h 127.0.0.1 -uroot -p123 --silent"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      mariadb12:
        image: mariadb:12
        env:
          MYSQL_DATABASE: fastschema
          MYSQL_ROOT_PASSWORD: 123
        ports:
          - 3311:3306
        options: >-
          --health-cmd "mariadb-admin ping -h 127.0.0.1 -uroot -p123 --silent"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
      postgres10:
        image: postgres:10
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres11:
        image: postgres:11
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5434:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres12:
        image: postgres:12.3
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5435:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres13:
        image: postgres:13.1
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5436:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres14:
        image: postgres:14
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5437:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres15:
        image: postgres:15
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5438:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres16:
        image: postgres:16
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5439:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres17:
        image: postgres:17
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5440:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres18:
        image: postgres:18
        env:
          POSTGRES_DB: fastschema
          POSTGRES_PASSWORD: 123
        ports:
          - 5441:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.3
      - name: Test
        run: gotestsum -f testname -- ./... -race -count=1 -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.go == '1.25.x' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          slug: fastschema/fastschema
