name: Build docker image on release new tag
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/fastschema/fastschema
          tags: |
            type=semver,pattern={{ version }},value=${{ github.event.inputs.version }}
            type=semver,pattern={{ major }}.{{ minor }},value=${{ github.event.inputs.version }}
            type=semver,pattern={{ major }},value=${{ github.event.inputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ github.event.inputs.version }}
          platforms: linux/amd64,linux/arm64,linux/armv7,darwin/amd64,darwin/arm64,windows/amd64,windows/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
